#version 460
#extension GL_NVX_raytracing : require

layout(binding = 0) uniform accelerationStructureNVX topLevelAS;
layout(binding = 1, rgba8) uniform image2D image;

layout(location = 0) rayPayloadNVX float hitValue;

void main() 
{
    const vec2 pixelCenter = vec2(gl_LaunchIDNVX.xy) + vec2(0.5);
    const vec2 inUV = pixelCenter/vec2(gl_LaunchSizeNVX.xy);

    imageStore(image, ivec2(gl_LaunchIDNVX.xy), vec4(inUV.x, inUV.y, 0.0, 0.0));
}
